[package]
name = "bevy_terrain"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.15", features = ["file_watcher", "jpeg", "bevy_mesh_picking_backend"] }
bevy_flycam = "0.15"
bevy-inspector-egui = "0.28"

gltf = "1.3"
image = "0.25"
rayon = "1.10"
itertools = "0.14"

